### ISSUE TITLE
Visable api key

### ISSUE THREAD

**Issue by Hay1tsme** [cnguy/OneTricks#5]
Not sure if this was intended but your api key for this application is visible (https://github.com/cnguy/OneTricks/tree/master/client/public/riot.txt)

**Comment by cnguy** [comment]
Hi, thank you for the warning! Fortunately, it is not my API key. That is just for verifying apps.

**Comment by Hay1tsme** [comment]
Ohh I understand, you're welcome!

**Comment by cnguy** [comment]
Thanks again. :) Gonna delete that file since it's been long verified.
